package vo;

public class CartVo {

}

/*CREATE TABLE CARTS(
		 CART_IDX NUMBER(5),
		 USER_ID VARCHAR2(20),
		 PRODUCT_CODE VARCHAR2(20),
		 ORDER_COUNT NUMBER(6),
		 CART_DATE DATE,
		 CONSTRAINT CARTS_CART_ID_PK PRIMARY KEY (CART_IDX)
		)*/