package vo;

public class Category1Vo {

}

/*CREATE TABLE CATEGORY1(
		 CTGRY_CODE VARCHAR2(20),
		 CTGRY_NAME VARCHAR2(60),
		 CONSTRAINT CATEGORY1_CTGRY_CODE_PK PRIMARY KEY (CTGRY_CODE)
		)*/